version: "2"         # required to adjust maintainability checks
checks:
  method-complexity:
    config:
      threshold: 25  # default is 5
  method-lines:
    config:
      threshold: 50  # default is 25
  return-statements:
    config:
      threshold: 5   # default is 4
plugins:
  structure:
    enabled: true
  fixme:
    enabled: true
  eslint:
    enabled: false
    config:
      extensions:
      - .ts
      - .js
      - .jsx
      - .mjs
  duplication:
    enabled: true
